### ISSUE TITLE
KnexTimeoutError: Knex: Timeout acquiring a connection

### ISSUE THREAD

**Issue by lexcorp** [UNL-CCFL/jawoot#18]
[root@xyz jawoot]# knex migrate:latest
Using environment: development
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/tmp/jawoot/node_modules/knex/lib/client.js:347:26)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/usr/lib/node_modules/knex/bin/cli.js:232:32)

**Comment by lexcorp** [comment]
Solved: This is related with PostgreSQL version installed, I update to postgresql 13 on centos 7
